config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :writings, except: [ :new, :index ]
  resources :projects, except: [ :new, :index ]
  get 'dashboard', to: "pages#dashboard", as: :dashboard
  get 'works', to: "pages#works", as: :works
  get 'about', to: "pages#about", as: :about
  get 'contact', to: "pages#contact", as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :cover
  has_many_attached :photos

  # validations
  validates :project_type, inclusion: { in: %w(exhibition project) }
  validates :project_type, presence: true
  validates :title, presence: true
  validates :tagline, presence: true
  validates :date, presence: true
  validates :project_type, presence: true

  # action text
  has_rich_text :rich_body

  # friendly URLS
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # cloudinary
  has_one_attached :avatar
  has_one_attached :cv
  has_many_attached :moodboard

  # action text
  has_rich_text :rich_bio
end

app/models/writing.rb
class Writing < ApplicationRecord
  belongs_to :user
  # validations
  validates :title, presence: true
  validates :tagline, presence: true
  validates :date, presence: true
  # cloudinary
  has_one_attached :cover
  # action text
  has_rich_text :rich_body
  # friendly URLS
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:bio, :rich_bio, :quotes, :contact_mail, :avatar, :cv, moodboard: [] ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :rich_bio, :quotes, :contact_mail, :avatar, :cv, moodboard: [] ])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, except: [:dashboard]

  def home
    @quotes = User.find_by(admin: true).quotes || "Make sure to add some funky quotes on your dashboard"
    # retrieve the random key from one of the moodboard pictures to showcase on the front page
    @image = User.find_by(admin: true).moodboard_attachments.sample
  end

  def works
    # this could be faster
    @works = (Writing.all.order(date: :desc) + Project.all.order(:date)).sort_by(&:date).reverse!
    @quotes = User.find_by(admin: true).quotes
  end

  def dashboard
    @user = current_user
    @avatar = User.find_by(admin: true).avatar.key
    @writings = Writing.all.order(date: :desc)
    @writing = Writing.new
    @projects = Project.all.order(date: :desc)
    @project = Project.new
    @cv = User.find_by(admin: true).cv.key
    @moodboard = User.find_by(admin: true).moodboard
  end

  def contact
    @quotes = User.find_by(admin: true).quotes
    @mail = User.find_by(admin: true).contact_mail
  end

  def about
    @bio = User.find_by(admin: true).rich_bio
    @cv = User.find_by(admin: true).cv.key
    @avatar = User.find_by(admin: true).avatar.key
    @quotes = User.find_by(admin: true).quotes
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, except: [:create, :edit, :update, :destroy]
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def show
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save!
    # no need for app/views/projects/create.html.erb
    redirect_to project_path(@project)
    else
      render "pages/dashboard", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @project.update(project_params)

    # no need for app/views/projects/update.html.erb
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy

    # no need for app/views/projects/destroy.html.erb
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title,
                                    :tagline,
                                    :artists,
                                    :institution_name,
                                    :project_type,
                                    :institution_address,
                                    :rich_body,
                                    :cover,
                                    :date,
                                    :end_date,
                                    photos: [])
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  skip_before_action :authenticate_user!, except: [:create, :edit, :update, :destroy]
  before_action :find_writing, only: [:show, :edit, :update, :destroy]

  def show
    @quotes = User.find_by(admin: true).quotes
  end

  def create
    @writing = Writing.new(writing_params)
    @writing.user = current_user
    if @writing.save!
      redirect_to writing_path(@writing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @writing.update(writing_params)
    if @writing.save!
      redirect_to writing_path(@writing)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @writing.destroy

    redirect_to dashboard_path
  end

  private

  def find_writing
    @writing = Writing.friendly.find(params[:id])
  end

  def writing_params
    params.require(:writing).permit(:title, :tagline, :date, :rich_body, :cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_author
    content_for?(:meta_author) ? content_for(:meta_author) : DEFAULT_META["meta_author"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# PWA %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%# responsive design %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%# Favicon %>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🦠</text></svg>">
    <%# Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@100;400;800&display=swap" rel="stylesheet">
    <%# Meta Tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# SCSS and JS entry point %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="statement container d-flex flex-column">

    <% if @bio %>
      <%= @bio %>
    <% end %>

    <% if @cv %>
      <a id="link-red" target="_blank" href="<%= cl_image_path @cv %>">Download my cv</a>
    <% end %>

    <br>

    <% if @avatar %>
      <%= cl_image_tag(@avatar, alt: "portrait of Antoine Champenois") %>
    <% end %>

  </div>
</div>

<%= render  "shared/footer" %>

app/views/pages/contact.html.erb
<div class="fullscreen d-flex justify-content-center align-items-center">
  <a href="mailto:<%= @mail %>"><%= @mail %></a>
</div>

<%= render  "shared/footer" %>

app/views/pages/dashboard.html.erb
<div class="container margin-from-navbar dashboard-color">
<br>
<br>
<br>
  <div class="">
    <%# nav start %>
      <nav class="nav nav-tabs">
        <a class="nav-link active link-font" aria-current="page" href="#writings" data-bs-toggle="tab">📑</a>
        <a class="nav-link link-font" href="#newwriting" data-bs-toggle="tab">✍🏻</a>
        <a class="nav-link link-font" aria-current="page" href="#projects" data-bs-toggle="tab">🖼</a>
        <a class="nav-link link-font" href="#newproject" data-bs-toggle="tab">✍🏻</a>
        <a class="nav-link link-font" href="#profile" data-bs-toggle="tab">👱🏻‍♂️</a>
        <a class="nav-link link-font" href="#moodboard" data-bs-toggle="tab">💡</a>
      </nav>
    <%# nav end %>

    <%# content start %>
    <div class="container-60">
      <div class="d-flex justify-content-end pe-2 pt-1 text-end">
      <div>
        <%= link_to  " X sign out", destroy_user_session_path, data: { "turbo-method": :delete }, id: "link-red" %>
      </div>
    </div>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="writings" role="tabpanel">
        <%= render  "pages/dashboard/writings_tab" %>
      </div>

      <div class="tab-pane fade show" id="newwriting" role="tabpanel">
        <h2 class="mb-4">New Writing</h2>
        <%= render  "writings/new" %>
      </div>

      <div class="tab-pane fade show" id="projects" role="tabpanel">
        <%= render  "pages/dashboard/projects_tab" %>
      </div>

      <div class="tab-pane fade show" id="newproject" role="tabpanel">
      <h2 class="mb-4">New Project</h2>
        <%= render  "/projects/new" %>
      </div>

      <div class="tab-pane fade show" id="profile" role="tabpanel">
        <%= render  "pages/dashboard/profile_tab" %>
      </div>

        <div class="tab-pane fade show" id="moodboard" role="tabpanel">
        <%= render  "pages/dashboard/moodboard_tab" %>
      </div>
    </div>
    <%# content end %>
  </div>
</div>

app/views/pages/dashboard/_moodboard_tab.html.erb
<h2 class="mb-3">Your Moodboard</h2>
<%= simple_form_for(@user, url: registration_path(@user), html: { method: :put }, data: { controller: "preview" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :moodboard,
                as: :file,
                label: :moodboard,
                  input_html: {
                  multiple: true,
                  class: 'd-none',
                  data: { preview_target: "input" }
                }, label_html: { class: 'upload-photo'}, label: '📷 Add your moodboard' %>
    <%= f.input :current_password,
                hint: "we need your current password to confirm your changes",
                label: false,
                placeholder: "Your current password",
                required: true,
                input_html: { autocomplete: "current-password" } %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Update", class: "w-100 dashboard-button", id: "text-white" %>
  </div>

  <%# MOODBOARD PREVIEW START %>
  <div class="w-100">
    <ul class="masonry masonry-col-2 w-100 pt-3 list-style-none" id="previous">
      <div class="existing-moodboard-wrapper" data-preview-target="previous">
        <% if @moodboard %>
            <% @moodboard.each do |pin| %>
              <li class="item" ><%= cl_image_tag pin.key %></li>
            <% end %>
        <% end %>
      </div>
    </ul>
    <ul class="masonry masonry-col-2 w-100 pt-3 list-style-none" id="preview" data-preview-target="list">


    </ul>
    <%= image_tag "",
                width: 100,
                data: { preview_target: "preview" } %>
  </div>
  <%# MOODBOARD PREVIEW END %>
  <br>
  <br>
  <br>
<% end %>

app/views/pages/dashboard/_profile_tab.html.erb
<h2 class="mb-3">Your Profile</h2>
<%= simple_form_for(@user, url: registration_path(@user), html: { method: :put }, data: { controller: "preview" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="d-flex w-100 justify-content-between">
      <%= f.input :avatar,
                  as: :file,
                  label: :avatar,
                  input_html: {
                  class: 'd-none',
                  data: { preview_target: "input" }
                }, label_html: { class: 'upload-photo'}, label: '📷 Add a portrait' %>
      <div class="w-50">
        <%= image_tag "",
                    width: 100,
                    class: "hidden",
                    data: { preview_target: "preview" } %>
      </div>
    </div>
    <%= f.input :cv, as: :file,
                input_html: {
                  class: 'd-none',
                  data: { preview_target: "input" }
                },
                label_html: {
                  class: 'upload-photo mt-3'
                  },
                label: '📝 Add your CV' %>
    <% if @cv %>
      <a id="cv-downloader" target="_blank" href="<%= cl_image_path @cv %>">Download my cv</a>
    <% end %>
    <br>
    <br>
    <%= f.rich_text_area :rich_bio,
                # label: false,
                placeholder: "Bio",
                required: false %>
    <%= f.input :contact_mail,
                # label: false,
                placeholder: "Contact mail",
                hint: "This is the mail you want to show on the contact page",
                required: false %>
    <%= f.input :quotes,
                # label: false,
                placeholder: "Quotes",
                hint: "Say something fun for your footer!",
                required: false %>
    <%= f.input :email, required: true, autofocus: true %>

    <%= f.input :password,
                hint: "leave it blank if you don't want to change it",
                required: false,
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: false,
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :current_password,
                hint: "we need your current password to confirm your changes",
                required: true,
                input_html: { autocomplete: "current-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update", class: "w-100 dashboard-button", id: "text-white" %>
  </div>
  <br>
  <br>
  <br>
<% end %>

app/views/pages/dashboard/_projects_tab.html.erb
<ol class="ol-kill-padding">
  <h2 class="mb-3">Your Projects</h2>
  <% if @projects %>
    <% @projects.each do |project| %>
      <%= link_to project_path(project) do %>
        <div class="card-product">
          <% if project.cover %>
            <%= cl_image_tag(project.cover.key) %>
          <% end %>
          <div class="card-product-infos">
            <div class="d-flex w-100 justify-content-between">
              <h2><%= project.title %></h2>
              <div class="d-flex dasboard_card_icons">
                <%= link_to  "🖋", edit_project_path(project) %>
                    <span>&nbsp;&nbsp;</span>
                <%= link_to  "🗑", project_path(project),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>
            </div>
            <span class="work-date"><%= project.date.strftime("%d of %B, %Y") + " | " %></span>
            <span class="work-text">project</span>
            <p style="color: black !important;"><%= project.tagline%></p>
          </div>
        </div>
      <% end  %>
    <% end %>
  <% else %>
    <p>You have no projects yet!</p>
  <% end %>
</ol>

app/views/pages/dashboard/_writings_tab.html.erb
<ol class="ol-kill-padding">
  <h2 class="mb-3">Your Writings</h2>
  <% if @writings %>
    <% @writings.each do |writing| %>
      <%= link_to writing_path(writing) do %>
        <div class="card-product">
          <%= cl_image_tag(writing.cover.key) %>
          <div class="card-product-infos">
            <div class="d-flex w-100 justify-content-between">
              <h2><%= writing.title %></h2>
              <div class="d-flex dasboard_card_icons">
                <%= link_to  "🖋", edit_writing_path(writing) %>
                    <span>&nbsp;&nbsp;</span>
                <%= link_to  "🗑", writing_path(writing),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>
            </div>
            <span class="work-date"><%= writing.date.strftime("%d of %B, %Y") + " | " %></span>
            <span class="work-text">text</span>
            <p style="color: black !important;"><%= writing.tagline.truncate(160, ommission: "...") %></p>
          </div>
        </div>
      <% end  %>
    <% end %>
  <% else %>
    <p> You have not texts yet!</p>
  <% end %>

</ol>

app/views/pages/home.html.erb
<% if @image %>
  <div class="fullscreen fullscreen-img" style="background-image: url('<%= cl_image_path @image.key %>')">
  </div>
<% else %>
  <div class="fullscreen fullscreen-img" style="background-image: url('<%#= cl_image_path @image %>https://source.unsplash.com/')">
  </div>
<% end %>

<%= render  "shared/footer" %>

app/views/pages/works.html.erb
<div class="writings-wrapper">
  <div class="masonry margin-from-quotes">
    <% if @works %>
      <% @works.each do |work| %>
        <% if work.class == Writing %>
          <%= link_to  writing_path(work) do %>
            <div class="item">
              <%= cl_image_tag(work.cover.key) %>
              <h2><%= work.title %></h2>
              <span class="work-date"><%= work.date.strftime("%d of %B, %Y") + " | " %></span>
              <span class="work-text">text</span>
              <p><%= work.tagline.truncate(100, ommission: "...")  %></p>
            </div>
          <% end %>
        <% elsif work.class == Project %>
          <%= link_to  project_path(work) do %>
            <div class="item">
              <%= cl_image_tag(work.cover.key) %>
              <h2><%= work.title %></h2>
              <span class="work-date"><%= work.date.strftime("%d of %B, %Y") + " | " %></span>
              <span class="work-text"><%= work.project_type %></span>
              <p><%= work.tagline.truncate(100, ommission: "...")  %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<%= render  "shared/footer" %>

app/views/projects/_new.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.input :title, placeholder: "Title" %>
  <%= f.input :tagline, placeholder: "Tagline" %>
  <%= f.input :project_type, collection: %w(exhibition project) %>
  <%= f.rich_text_area :rich_body, placeholder: "Text" %>
  <%= f.input :institution_name, placeholder: "Institution name" %>
  <%= f.input :institution_address, placeholder: "Institution address" %>
  <%= f.input :artists, placeholder: "Artists included" %>
  <%= f.input :date, html5: true, input_html: { data: { controller: "flatpickr" } }   %>
  <%= f.input :end_date, html5: true, input_html: { data: { controller: "flatpickr" } }   %>
  <%= f.input :cover, as: :file, label: :Photo %>
  <%# custom inputs start %>
  <div class="mb-3">
    <%= label_tag(:caption, "photo caption", class: "form-label required", required: :true) do %>
      Photo Caption <abbr title="required">*</abbr>
    <% end %>
    <%= text_field_tag(:caption, "", class: "form-control", required: :true) %>
  </div>
  <%# custom inputs end %>
  <%= f.input :photos,
                as: :file,
                input_html: { multiple: true,
                  class: 'd-none',
                  data: { preview_target: "input" }
                }, label_html: { class: 'upload-photo'}, label: '📷 Gallery pictures' %>
  <div class="btn w-100 dashboard-button">
    <%= f.submit %>
  </div>
  <br>
  <br>
  <br>
<% end %>

app/views/projects/show.html.erb
<% content_for :meta_title, "#{@project.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "#{@project.tagline} by Antoine Champenois" %>
<% content_for :meta_author, "Antoine Champenois" %>
<% content_for :meta_image, cl_image_path(@project.cover.key) if @project.cover.attached? %>

<div class="container-main margin-from-navbar">

  <div class="article-top">
    <div class="article-header">

      <div class="header-info-project">

        <% if @project.institution_name %>
          <p class="header-author" style="font-size: smaller;"><%= @project.institution_name.upcase %></p>
        <% end %>

        <p class="header-date"><%= @project.date.strftime("%-d %B %y") %>
          <% if @project.end_date %>
            <span class="text-dark">to</span> <%= @project.end_date.strftime("%-d %B %y") %>
          <% end %>
        </p>
      </div>

      <div class="header-title">
        <div class="d-flex">
          <h1><%= @project.title.upcase %></h1>
          <% if current_user && current_user.admin? %>
            <%= link_to  "🖋", edit_project_path(@project) %>
          <% end %>
        </div>

        <% if !@project.artists.empty? %>
          <p style="color: grey; font-size: smaller;">with <%= @project.artists %></p>
        <% end %>

      </div>

    </div>

      <% if @project.cover.attached? %>
        <%= cl_image_tag(@project.cover.key) %>
      <% else %>
        <img src="https://source.unsplash.com/random" alt="">
      <% end %>



  </div>


  <p id="project-text"><%= @project.rich_body %></p>
  <div class="border-bottom border-dark mb-4"></div>

  <div class="masonry-grid" data-controller="lightbox">

  <% if  @project.photos.attached? %>
    <% @project.photos.each do |photo| %>
      <%= cl_image_tag photo.key, class: "grid-item"%>
    <% end %>
    </div>
    <div class="article-border-bottom mt-2"></div>
  <% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="home_footer">
  <p class="footer_quote" id="footer_animation">
    <%= (@quotes + "  | ") * 100 %>
  </p>
</footer>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="navbar navbar_main_styles sticky-top">
  <div class="nav_content">
    <%= link_to  root_path do %>
      <h1 id="nav-logo">ANTOINE CHAMPENOIS</h1>
    <% end %>
    <ul class="nav_links d-flex">
      <li><%= link_to  "WORKS", works_path %></li>
      <li><%= link_to  "ABOUT", about_path %></li>
      <li><%= link_to  "CONTACT", contact_path %></li>
      <% if current_user && current_user.admin? %>
        <li><%= link_to  "DASHBOARD", dashboard_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/writings/edit.html.erb
<div class="container pt-5 my-5">
  <%= render  "writings/shared/form_edit" %>
</div>

app/views/writings/show.html.erb
<% content_for :meta_title, "#{@writing.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "#{@writing.tagline} by Antoine Champenois" %>
<% content_for :meta_author, "Antoine Champenois" %>
<% content_for :meta_image, cl_image_path(@writing.cover.key) if @writing.cover.attached? %>


<div class="container-main margin-from-navbar">

  <div class="article-top">
    <div class="article-header">

      <div class="header-info">
        <p class="header-date"><%= @writing.date.strftime("%d of %B %Y") %></p>
      </div>

      <div class="header-title">
        <h2><%= @writing.title.upcase %></h2>
        <% if current_user && current_user.admin? %>
          <%= link_to  "🖋", edit_writing_path(@writing) %>
        <% end %>
        <p style="color: grey;"><%= @writing.tagline %></p>
      </div>

    </div>

    <% if @writing.cover.attached? %>
      <%= cl_image_tag @writing.cover.key %>
    <% else %>
      <img src="https://source.unsplash.com/random" alt="">
    <% end %>

  </div>

  <div class="container-60">
    <p style="color: grey !important;"><%= @writing.rich_body %></p>
  </div>
  <div class="article-border-bottom"></div>


</div>